# Generated by Django 4.0 on 2022-01-16 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('actions', models.CharField(choices=[('display', 'Display'), ('spinHeart', 'Spin The Heart'), ('blinkLEDs', 'Blink LEDS')], default='display', max_length=100)),
                ('read', models.BooleanField(default=False)),
                ('highlighted', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='auth.user')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
